import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Generates a PDF from a recipe card element and downloads it
 * @param recipeCardElement - The DOM element of the recipe card to convert to PDF
 * @param recipeName - The name of the recipe for the PDF filename
 */
export const generateRecipePDF = async (
  recipeCardElement: HTMLElement,
  recipeName: string
): Promise<void> => {
  // Find elements to hide
  const imageGenButton = recipeCardElement.querySelector('#generate-image-button') as HTMLElement | null;
  const actionButtons = recipeCardElement.querySelector('#action-buttons-container') as HTMLElement | null;
  
  // Store original styles
  const originalImageBtnStyle = imageGenButton?.style.display;
  const originalActionBtnsStyle = actionButtons?.style.display;

  try {
    // Hide elements before capture
    if (imageGenButton) imageGenButton.style.display = 'none';
    if (actionButtons) actionButtons.style.display = 'none';

    // Add a small delay to ensure styles are applied before capture (optional, might help)
    await new Promise(resolve => setTimeout(resolve, 50)); 

    // Create a canvas from the recipe card element
    const canvas = await html2canvas(recipeCardElement, {
      scale: 2, // Higher scale for better quality
      useCORS: true, // Allow images from other domains
      logging: false,
      backgroundColor: '#ffffff', // White background
    });

    // Calculate dimensions for A4 page (210mm x 297mm)
    // Define constants
    const pdfWidth = 210; // A4 width in mm
    const margin = 15; // Increased margin
    const contentWidth = pdfWidth - 2 * margin;
    const titleHeight = 15; // Estimated space for title + top margin
    const footerHeight = 15; // Estimated space for footer line + text + bottom margin
    
    // Calculate proportional image dimensions based on contentWidth
    const imgWidth = contentWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    // Calculate required page height
    const pageHeight = titleHeight + imgHeight + footerHeight; 
    
    // Center the image horizontally
    const xPos = margin; // Place image starting at left margin
    
    // Create PDF with custom dimensions
    const pdf = new jsPDF('p', 'mm', [pdfWidth, pageHeight]);
    
    // Add title 
    pdf.setFontSize(18); 
    pdf.setTextColor(46, 125, 50); 
    pdf.text(recipeName, pdfWidth / 2, margin + 5, { align: 'center' }); // Position title within top margin
    
    // Add the recipe image (position below title area)
    pdf.addImage(
      canvas.toDataURL('image/png'),
      'PNG',
      xPos, 
      titleHeight, // Start image below the title area
      imgWidth,
      imgHeight
    );
    
    // Add footer line
    const footerLineY = pageHeight - footerHeight + 5; // Position line relative to bottom
    pdf.setDrawColor(200, 200, 200); 
    pdf.line(margin, footerLineY, pdfWidth - margin, footerLineY); 

    // Add footer text
    pdf.setFontSize(9); 
    pdf.setTextColor(150, 150, 150); 
    pdf.text('Generated by Sprout Notes 🌱 - Ideas That Grow', pdfWidth / 2, footerLineY + 5, { align: 'center' }); 
    
    // Download the PDF
    pdf.save(`${recipeName.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF');
  } finally {
    // Restore original styles
    if (imageGenButton && originalImageBtnStyle !== undefined) imageGenButton.style.display = originalImageBtnStyle;
    if (actionButtons && originalActionBtnsStyle !== undefined) actionButtons.style.display = originalActionBtnsStyle;
  }
};

/**
 * Shares a recipe using the Web Share API if available,
 * or falls back to copying a link to clipboard
 * @param recipe - The recipe object to share
 * @param shareUrl - The URL to share (optional, defaults to current URL)
 */
export const shareRecipe = async (
  recipe: { name: string; description?: string },
  shareUrl?: string
): Promise<void> => {
  const url = shareUrl || window.location.href;
  const title = `Sprout Notes: ${recipe.name}`;
  const text = recipe.description || `Check out this delicious vegan recipe: ${recipe.name}`;
  
  // Check if Web Share API is available
  if (navigator.share) {
    try {
      await navigator.share({
        title,
        text,
        url,
      });
      return;
    } catch (error) {
      // If user cancels or share fails, fall back to clipboard
      console.log('Share canceled or failed, falling back to clipboard');
    }
  }
  
  // Fallback: Copy to clipboard
  try {
    await navigator.clipboard.writeText(`${title}\n\n${text}\n\n${url}`);
    alert('Recipe link copied to clipboard!');
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    alert('Could not share recipe. Please copy the URL manually.');
  }
};
