import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { corsHeaders, handleCors, addCorsHeaders } from "../_shared/cors.ts";

// Interface for image generation request body
interface ImageGenerationRequestBody {
  recipeName: string;
  ingredients?: string[];
  style?: string;
}

// Get API key from environment variables
const apiKey = Deno.env.get("OPENROUTER_API_KEY");

if (!apiKey) {
  console.error("OPENROUTER_API_KEY environment variable is not set");
}

serve(async (req) => {
  // Handle CORS preflight request
  const corsResponse = handleCors(req);
  if (corsResponse) {
    return corsResponse;
  }

  try {
    // Only allow POST requests
    if (req.method !== "POST") {
      return new Response(JSON.stringify({ error: "Method not allowed" }), {
        status: 405,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Parse request JSON
    const requestData: ImageGenerationRequestBody = await req.json();
    const { recipeName, ingredients = [], style = "food photography" } = requestData;

    if (!recipeName) {
      return new Response(
        JSON.stringify({ error: "Invalid request: recipeName is required" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Build a detailed prompt for high-quality food photography
    const ingredientList = ingredients.length > 0
      ? `featuring ${ingredients.slice(0, 5).join(', ')}`
      : '';

    const prompt = `Generate a beautiful, appetizing photograph of a vegan dish called "${recipeName}" ${ingredientList}.

The image should have:
- Professional food photography styling
- Natural soft lighting from the side
- Clean white ceramic plate or rustic wooden board
- Fresh, vibrant colors of vegetables and ingredients
- Shallow depth of field for artistic effect
- Restaurant-quality plating and presentation
- Appropriate garnishes (fresh herbs, seeds, or microgreens)
- Clean, minimal background (light wood, marble, or white)

Style: ${style}, editorial quality, high resolution, warm inviting tones, Instagram-worthy presentation.`;

    console.log("Calling OpenRouter API for image generation:", recipeName);
    console.log("Prompt:", prompt);

    // Call OpenRouter API with Nano Banana Pro (Gemini 3 Pro Image Preview)
    const openRouterResponse = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
        "HTTP-Referer": "https://sprouts-app.com",
        "X-Title": "Sprouts App - Vegan Recipe Generator",
      },
      body: JSON.stringify({
        model: "google/gemini-3-pro-image-preview",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        modalities: ["image", "text"],
        image_config: {
          aspect_ratio: "4:3"
        }
      }),
    });

    if (!openRouterResponse.ok) {
      const errorText = await openRouterResponse.text();
      console.error("OpenRouter API error:", openRouterResponse.status, errorText);
      throw new Error(`OpenRouter API error: ${openRouterResponse.status} - ${errorText}`);
    }

    // Parse OpenRouter response
    const openRouterData = await openRouterResponse.json();
    console.log("OpenRouter response received");

    // Extract the image from the response
    // Images are in choices[0].message.images array as base64 data URLs
    const message = openRouterData.choices?.[0]?.message;

    if (!message) {
      throw new Error("Invalid response from OpenRouter API: Missing message");
    }

    // Check for images in the response
    let imageUrl: string | null = null;

    if (message.images && Array.isArray(message.images) && message.images.length > 0) {
      // Images are typically in format: { type: "image_url", image_url: { url: "data:image/png;base64,..." } }
      const imageData = message.images[0];
      if (imageData?.image_url?.url) {
        imageUrl = imageData.image_url.url;
      } else if (typeof imageData === 'string') {
        // Sometimes it's just a string URL
        imageUrl = imageData;
      }
    }

    // Also check for base64 in content if images array not found
    if (!imageUrl && message.content) {
      // Check if content contains a data URL
      const dataUrlMatch = message.content.match(/data:image\/[^;]+;base64,[^\s"']+/);
      if (dataUrlMatch) {
        imageUrl = dataUrlMatch[0];
      }
    }

    if (!imageUrl) {
      console.error("No image found in OpenRouter response:", JSON.stringify(openRouterData, null, 2));
      throw new Error("No image generated by OpenRouter API");
    }

    console.log("Image generated successfully for:", recipeName);

    // Return the image URL (base64 data URL)
    return addCorsHeaders(
      new Response(JSON.stringify({
        imageUrl,
        recipeName,
        message: "Image generated successfully"
      }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      })
    );

  } catch (error) {
    console.error("Error processing image generation request:", error);

    return addCorsHeaders(
      new Response(
        JSON.stringify({
          error: error instanceof Error ? error.message : "Unknown error occurred",
          fallback: true // Signal to frontend to use fallback
        }),
        {
          status: 500,
          headers: { "Content-Type": "application/json" },
        }
      )
    );
  }
});
